// samples/Todo.Frontends/svelte/src/components/AppHeader.svelte
<script lang="ts">
  interface Props {
    title: string;
    subtitle: string;
    connected: boolean;
    status: string;
  }

  let { title, subtitle, connected, status }: Props = $props();
</script>

<header class="mb-4">
  <div class="d-flex flex-wrap gap-2 justify-content-between align-items-start">
    <div>
      <span class="framework-badge badge text-bg-danger mb-2">Svelte</span>
      <h1 class="display-6 fw-semibold mb-1">{title}</h1>
      <p class="text-secondary mb-0">{subtitle}</p>
    </div>
    <span
      class:badge={true}
      class:text-bg-success={connected}
      class:text-bg-secondary={!connected}
    >{status}</span>
  </div>
</header>

// samples/Todo.Frontends/react/src/components/AppHeader.tsx
import { useMvvmSnapshot } from "@webuitoolkit/mvvm-react";

export interface AppHeaderProps {
  readonly title: string;
  readonly subtitle: string;
}

export function AppHeader({ title, subtitle }: AppHeaderProps) {
  const snapshot = useMvvmSnapshot();
  return (
    <header className="mb-4">
      <div className="d-flex flex-wrap gap-2 justify-content-between align-items-start">
        <div>
          <span className="framework-badge badge text-bg-primary mb-2">React</span>
          <h1 className="display-6 fw-semibold mb-1">{title}</h1>
          <p className="text-secondary mb-0">{subtitle}</p>
        </div>
        <span className={`badge ${snapshot.synchronized ? "text-bg-success" : "text-bg-secondary"}`}>
          {snapshot.synchronized ? `Connected · r${snapshot.revision}` : snapshot.phase}
        </span>
      </div>
    </header>
  );
}
