// samples/Todo.Frontends/react/src/simple/SimpleTodo.tsx
import type { SimpleTodoContract } from "../../../shared/contracts";
import { AppHeader } from "../components/AppHeader";
import { useSimpleTodo } from "./useSimpleTodo";

export function SimpleTodo({ todo }: { readonly todo: SimpleTodoContract }) {
  const model = useSimpleTodo(todo);
  return (
    <div className="app-shell simple-shell">
      <AppHeader
        title="Simple ToDo"
        subtitle="One shared C# ViewModel, rendered through React hooks."
      />
      <section className="card hero-card">
        <div className="card-body p-4">
          <form className="input-group mb-4" onSubmit={model.submit}>
            <label className="visually-hidden" htmlFor="new-title">New task</label>
            <input
              id="new-title"
              className="form-control"
              value={model.title}
              maxLength={80}
              placeholder="What needs doing?"
              onChange={(event) => model.setTitle(event.currentTarget.value)}
            />
            <button
              className="btn btn-primary"
              disabled={model.pending || model.title.trim().length < 2 ||
                !model.snapshot.synchronized || !model.bindings.add.canExecute ||
                model.bindings.add.isRunning}
            >
              <i className="fa-solid fa-plus me-2" aria-hidden="true" />Add
            </button>
          </form>
          <div className="d-flex justify-content-between text-secondary small mb-3">
            <span>{model.items.length - model.completed} remaining</span>
            <span>{model.completed} completed</span>
          </div>
          <ul className="list-group list-group-flush">
            {model.items.map((item) => (
              <li
                className={`list-group-item px-0 todo-row ${item.isCompleted ? "completed" : ""}`}
                key={item.id}
              >
                <button
                  className="btn btn-sm btn-outline-primary rounded-circle"
                  aria-label={item.isCompleted ? "Mark active" : "Mark complete"}
                  onClick={() => void todo.toggle.execute(item.id).completion}
                >
                  <i
                    className={`fa-${item.isCompleted ? "solid fa-check" : "regular fa-circle"}`}
                    aria-hidden="true"
                  />
                </button>
                <span className="todo-title">{item.title}</span>
                <button
                  className="btn btn-sm btn-outline-danger todo-actions"
                  aria-label={`Remove ${item.title}`}
                  onClick={() => void todo.remove.execute(item.id).completion}
                >
                  <i className="fa-solid fa-trash" aria-hidden="true" />
                </button>
              </li>
            ))}
          </ul>
        </div>
      </section>
    </div>
  );
}

// samples/Todo.Frontends/angular/src/simple/simple-todo.component.ts
import {
  Component,
  computed,
  signal,
} from "@angular/core";
import { injectAngularMvvmApplication } from "@webuitoolkit/mvvm-angular";

import type { SimpleTodoContract } from "../../../shared/contracts";
import { AppHeaderComponent } from "../components/app-header.component";
import { injectSimpleTodoContract } from "../todo-bindings.g";

@Component({
  selector: "todo-app",
  standalone: true,
  imports: [AppHeaderComponent],
  templateUrl: "./simple-todo.component.html",
})
export class SimpleTodoComponent {
  private readonly application =
    injectAngularMvvmApplication<SimpleTodoContract>();
  protected readonly bindings = injectSimpleTodoContract();
  protected readonly todo = this.bindings.contract;
  protected readonly items = this.bindings.items;
  protected readonly title = signal("");
  protected readonly pending = signal(false);
  protected readonly completed = computed(() =>
    this.items().filter((item) => item.isCompleted).length);
  protected readonly canAdd = computed(() =>
    this.application.store.snapshot().synchronized &&
    this.bindings.add.canExecute() &&
    !this.bindings.add.isRunning() &&
    !this.pending() &&
    this.title().trim().length >= 2);

  protected setTitle(event: Event): void {
    this.title.set((event.currentTarget as HTMLInputElement).value);
  }

  protected async add(event: Event): Promise<void> {
    event.preventDefault();
    if (this.title().trim().length < 2) return;
    this.pending.set(true);
    try {
      await this.todo.newTitle.set(this.title());
      await this.bindings.add.execute().completion;
      this.title.set("");
    } finally {
      this.pending.set(false);
    }
  }
}

<div class="app-shell simple-shell">
  <todo-app-header
    title="Simple ToDo"
    subtitle="One shared C# ViewModel surfaced through Angular signals."
  />
  <section class="card hero-card">
    <div class="card-body p-4">
      <form class="input-group mb-4" (submit)="add($event)">
        <label class="visually-hidden" for="new-title">New task</label>
        <input
          id="new-title"
          class="form-control"
          [value]="title()"
          maxlength="80"
          placeholder="What needs doing?"
          (input)="setTitle($event)"
        >
        <button class="btn btn-primary" [disabled]="!canAdd()">
          <i class="fa-solid fa-plus me-2" aria-hidden="true"></i>Add
        </button>
      </form>
      <div class="d-flex justify-content-between text-secondary small mb-3">
        <span>{{ items().length - completed() }} remaining</span>
        <span>{{ completed() }} completed</span>
      </div>
      <ul class="list-group list-group-flush">
        @for (item of items(); track item.id) {
          <li
            class="list-group-item px-0 todo-row"
            [class.completed]="item.isCompleted"
          >
            <button
              class="btn btn-sm btn-outline-primary rounded-circle"
              [attr.aria-label]="item.isCompleted ? 'Mark active' : 'Mark complete'"
              (click)="todo.toggle.execute(item.id).completion"
            >
              <i
                [class]="item.isCompleted ? 'fa-solid fa-check' : 'fa-regular fa-circle'"
                aria-hidden="true"
              ></i>
            </button>
            <span class="todo-title">{{ item.title }}</span>
            <button
              class="btn btn-sm btn-outline-danger todo-actions"
              [attr.aria-label]="'Remove ' + item.title"
              (click)="todo.remove.execute(item.id).completion"
            >
              <i class="fa-solid fa-trash" aria-hidden="true"></i>
            </button>
          </li>
        }
      </ul>
    </div>
  </section>
</div>
